export const themeNavicatLightColors = {
  '--theme-generic-font': 'var(--tw-color-zinc-900)',
  '--theme-generic-font-hover': 'var(--tw-color-blue-600)',
  '--theme-generic-font-grayed': 'var(--tw-color-zinc-400)',
  '--theme-generic-font-error': 'var(--tw-color-red-600)',
  '--theme-generic-font-success': 'var(--tw-color-green-600)',
  '--theme-link-foreground': 'var(--tw-color-blue-600)',
  '--theme-content-background': 'white',

  '--theme-widget-panel-background': 'var(--tw-color-zinc-100)',
  '--theme-widget-panel-foreground': 'var(--tw-color-zinc-600)',
  '--theme-widget-icon-background-active': 'var(--tw-color-blue-100)',
  '--theme-widget-icon-foreground-active': 'var(--tw-color-blue-700)',
  '--theme-widget-icon-foreground-hover': 'var(--tw-color-blue-600)',
  '--theme-widget-icon-border-active': '1px solid var(--tw-color-blue-300)',
  '--theme-widget-icon-transition': 'background-color 120ms ease-in-out, color 120ms ease-in-out',

  '--theme-scrollbar-background': 'var(--tw-color-zinc-100)',
  '--theme-scrollbar-thumb-background': 'var(--tw-color-zinc-300)',
  '--theme-scrollbar-thumb-background-hover': 'var(--tw-color-zinc-400)',
  '--theme-scrollbar-corner-background': 'var(--tw-color-zinc-200)',

  '--theme-tabs-panel-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-tabs-panel-foreground': 'var(--tw-color-zinc-600)',
  '--theme-tabs-panel-active-foreground': 'var(--tw-color-zinc-900)',
  '--theme-tabs-panel-background': 'var(--tw-color-zinc-50)',
  '--theme-tabs-panel-active-background': 'white',
  '--theme-tabs-panel-item-background': 'var(--tw-color-zinc-100)',
  '--theme-tabs-panel-active-border': '2px solid var(--tw-color-blue-500)',
  '--theme-tabs-panel-active-border-db': 'none',

  '--theme-splitter-active': 'var(--tw-color-blue-500)',
  '--theme-splitter-button-background': 'var(--tw-color-zinc-100)',
  '--theme-splitter-button-background-active': 'var(--tw-color-zinc-200)',
  '--theme-splitter-button-foreground': 'var(--tw-color-zinc-800)',

  '--theme-sidebar-background': 'var(--tw-color-zinc-50)',
  '--theme-sidebar-background-hover': 'var(--tw-color-zinc-100)',
  '--theme-sidebar-background-active': 'var(--tw-color-zinc-200)',
  '--theme-sidebar-background-focused': 'var(--tw-color-blue-100)',
  '--theme-sidebar-foreground': 'var(--tw-color-zinc-800)',
  '--theme-sidebar-foreground-button': 'var(--tw-color-zinc-500)',
  '--theme-sidebar-foreground-grayed': 'var(--tw-color-zinc-400)',
  '--theme-sidebar-foreground-hover': 'var(--tw-color-blue-600)',
  '--theme-sidebar-section-background': 'var(--tw-color-zinc-100)',
  '--theme-sidebar-section-border': 'none',
  '--theme-sidebar-section-border-top': '1px solid var(--tw-color-zinc-200)',
  '--theme-sidebar-section-foreground': 'var(--tw-color-zinc-800)',
  '--theme-sidebar-border': '1px solid var(--tw-color-zinc-200)',

  '--theme-altsidebar-background': 'white',
  '--theme-altsidebar-background-grayed': 'var(--tw-color-zinc-50)',
  '--theme-altsidebar-background-hover': 'var(--tw-color-zinc-100)',
  '--theme-altsidebar-background-active': 'var(--tw-color-zinc-200)',
  '--theme-altsidebar-background-focused': 'var(--tw-color-blue-100)',
  '--theme-altsidebar-foreground': 'var(--tw-color-zinc-800)',
  '--theme-altsidebar-foreground-button': 'var(--tw-color-zinc-500)',
  '--theme-altsidebar-foreground-grayed': 'var(--tw-color-zinc-400)',
  '--theme-altsidebar-foreground-hover': 'var(--tw-color-blue-600)',
  '--theme-altsidebar-section-background': 'var(--tw-color-zinc-50)',
  '--theme-altsidebar-section-border': 'none',
  '--theme-altsidebar-section-border-top': '1px solid var(--tw-color-zinc-200)',
  '--theme-altsidebar-section-foreground': 'var(--tw-color-zinc-800)',
  '--theme-altsidebar-border': '1px solid var(--tw-color-zinc-200)',

  '--theme-searchbox-background': 'white',
  '--theme-searchbox-placeholder': 'var(--tw-color-zinc-400)',
  '--theme-searchbox-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-searchbox-background-filtered': 'var(--tw-color-amber-50)',
  '--theme-altsearchbox-background': 'white',
  '--theme-altsearchbox-placeholder': 'var(--tw-color-zinc-400)',
  '--theme-altsearchbox-border': '1px solid var(--tw-color-zinc-300)',

  '--theme-inlinebutton-foreground': 'var(--tw-color-zinc-500)',
  '--theme-inlinebutton-foreground-disabled': 'var(--tw-color-zinc-400)',
  '--theme-inlinebutton-foreground-hover': 'var(--tw-color-zinc-800)',
  '--theme-inlinebutton-circle-hover-background': 'var(--tw-color-zinc-200)',
  '--theme-inlinebutton-bordered-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-inlinebutton-bordered-hover-border': '1px solid var(--tw-color-zinc-400)',
  '--theme-inlinebutton-bordered-background':
    'linear-gradient(to bottom, var(--tw-color-zinc-50) 0%, var(--tw-color-zinc-100) 100%)',
  '--theme-inlinebutton-bordered-hover-background':
    'linear-gradient(to bottom, var(--tw-color-zinc-100) 0%, var(--tw-color-zinc-50) 100%)',

  '--theme-datagrid-background': 'var(--tw-color-zinc-50)',
  '--theme-datagrid-foreground': 'var(--tw-color-zinc-800)',
  '--theme-datagrid-foreground-grayed': 'var(--tw-color-zinc-400)',
  '--theme-datagrid-border-horizontal': '1px solid var(--tw-color-zinc-200)',
  '--theme-datagrid-border-vertical': '1px solid var(--tw-color-zinc-200)',
  '--theme-datagrid-cell-background': 'white',
  '--theme-datagrid-headercell-background': 'var(--tw-color-zinc-100)',
  '--theme-datagrid-cell-background-alt': 'var(--tw-color-blue-50)',
  '--theme-datagrid-cell-background-alt2': 'var(--tw-color-blue-50)',
  '--theme-datagrid-filter-background': 'var(--tw-color-zinc-100)',
  '--theme-datagrid-filter-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-datagrid-filter-ok-background': 'var(--tw-color-amber-50)',
  '--theme-datagrid-filter-error-background': 'var(--tw-color-rose-50)',
  '--theme-datagrid-modified-row-background': 'var(--tw-color-amber-50)',
  '--theme-datagrid-modified-cell-background': 'var(--tw-color-amber-100)',
  '--theme-datagrid-inserted-row-background': 'var(--tw-color-green-50)',
  '--theme-datagrid-deleted-row-background': 'var(--tw-color-red-50)',
  '--theme-datagrid-selected-cell-background': 'var(--tw-color-blue-100)',
  '--theme-datagrid-focused-cell-background': 'var(--tw-color-blue-100)',
  '--theme-datagrid-focused-cell-border-horizontal': '1px solid var(--tw-color-blue-400)',
  '--theme-datagrid-focused-cell-border-vertical': '1px solid var(--tw-color-blue-400)',
  '--theme-datagrid-selected-point-marker': 'var(--tw-color-blue-500)',
  '--theme-datagrid-corner-label-background': 'var(--tw-color-blue-100)',
  '--theme-datagrid-corner-label-border': '1px solid var(--tw-color-blue-300)',
  '--theme-datagrid-detail-header-background': 'var(--tw-color-blue-50)',
  '--theme-datagrid-detail-header-border': '1px solid var(--tw-color-blue-200)',
  '--theme-datagrid-cell-foreground-value-green': 'var(--tw-color-green-700)',

  '--theme-checkbox-check': 'var(--tw-color-zinc-100)',
  '--theme-checkbox-background': 'var(--tw-color-blue-600)',
  '--theme-checkbox-border': '1px solid var(--tw-color-zinc-400)',
  '--theme-checkbox-mark': 'white',
  '--theme-checkbox-background-disabled': 'var(--tw-color-zinc-100)',
  '--theme-checkbox-background-disabled-before': 'var(--tw-color-zinc-400)',
  '--theme-checkbox-hover-not-disabled': 'var(--tw-color-zinc-500)',
  '--theme-checkbox-background-inherited': 'var(--tw-color-zinc-300)',

  '--theme-table-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-table-cell-background': 'white',
  '--theme-table-cell-empty-background': 'var(--tw-color-zinc-50)',
  '--theme-table-cell-empty-foreground': 'var(--tw-color-zinc-400)',
  '--theme-table-header-background': 'var(--tw-color-zinc-100)',
  '--theme-table-selected-background': 'var(--tw-color-blue-100)',
  '--theme-table-active-background': 'var(--tw-color-zinc-100)',
  '--theme-table-hover-background': 'var(--tw-color-zinc-50)',
  '--theme-table-added-background': 'var(--theme-datagrid-inserted-row-background)',
  '--theme-table-changed-background': 'var(--theme-datagrid-modified-row-background)',
  '--theme-table-deleted-background': 'var(--theme-datagrid-deleted-row-background)',

  '--theme-cell-active-border': '2px solid var(--tw-color-blue-500)',
  '--theme-object-header-background': 'var(--tw-color-zinc-50)',

  '--theme-modal-background': 'white',
  '--theme-modal-header-background': 'var(--tw-color-blue-600)',
  '--theme-modal-footer-background': 'var(--tw-color-zinc-50)',
  '--theme-modal-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-modal-overlay-background': 'color-mix(in srgb, var(--tw-color-black) 40%, transparent)',
  '--theme-modal-shadow': '0 8px 32px color-mix(in srgb, var(--tw-color-black) 15%, transparent)',
  '--theme-modal-close-hover-background': 'color-mix(in srgb, white 20%, transparent)',

  '--theme-formbutton-foreground': 'white',
  '--theme-formbutton-border': '1px solid var(--tw-color-blue-600)',
  '--theme-formbutton-border-hover': '1px solid var(--tw-color-blue-500)',
  '--theme-formbutton-border-active': '1px solid var(--tw-color-blue-400)',
  '--theme-formbutton-background': 'var(--tw-color-blue-600)',
  '--theme-formbutton-background-disabled': 'var(--tw-color-zinc-300)',
  '--theme-formbutton-border-disabled': '1px solid var(--tw-color-zinc-300)',
  '--theme-formbutton-foreground-disabled': 'var(--tw-color-zinc-500)',
  '--theme-formbutton-background-hover': 'var(--tw-color-blue-700)',
  '--theme-formbutton-background-active': 'var(--tw-color-blue-800)',

  '--theme-outlinebutton-foreground': 'var(--tw-color-zinc-800)',
  '--theme-outlinebutton-border': '1px solid var(--tw-color-blue-600)',
  '--theme-outlinebutton-hover-foreground': 'var(--tw-color-blue-700)',
  '--theme-outlinebutton-hover-border': '1px solid var(--tw-color-blue-500)',

  '--theme-tabs-control-background': 'var(--tw-color-zinc-50)',
  '--theme-tabs-control-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-tabs-control-selected-background': 'white',
  '--theme-tabs-control-selected-border': '2px solid var(--tw-color-blue-500)',
  '--theme-inline-tabs-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-inline-tabs-border-active': '2px solid var(--tw-color-blue-500)',

  '--theme-toolstrip-background': 'var(--tw-color-zinc-50)',
  '--theme-toolstrip-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-foreground': 'var(--tw-color-zinc-700)',
  '--theme-panel-border-subtle': '1px solid var(--tw-color-zinc-200)',
  '--theme-panel-type-label-color': 'var(--tw-color-zinc-500)',
  '--theme-toolstrip-button-foreground-disabled': 'var(--tw-color-zinc-400)',
  '--theme-toolstrip-button-foreground-icon': 'var(--tw-color-zinc-600)',
  '--theme-toolstrip-button-background': 'var(--tw-color-zinc-50)',
  '--theme-toolstrip-button-background-hover': 'var(--tw-color-zinc-100)',
  '--theme-toolstrip-button-background-active': 'var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-border-hover': '1px solid var(--tw-color-zinc-300)',
  '--theme-toolstrip-button-border-disabled': '1px solid var(--tw-color-zinc-200)',
  '--theme-toolstrip-button-split-separator-border': '1px solid var(--tw-color-zinc-300)',

  '--theme-designer-background': 'white',
  '--theme-designer-item-background': 'var(--tw-color-zinc-50)',
  '--theme-designer-selection-marker': 'var(--tw-color-blue-700)',
  '--theme-designer-item-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-designer-stroke-color': 'var(--tw-color-zinc-400)',
  '--theme-designer-arrow-color': 'var(--tw-color-zinc-700)',
  '--theme-designer-select-reactangle-foreground': 'var(--tw-color-blue-500)',
  '--theme-designer-header-background-1': 'var(--tw-color-blue-200)',
  '--theme-designer-header-background-2': 'var(--tw-color-fuchsia-200)',
  '--theme-designer-header-background-3': 'var(--tw-color-red-200)',
  '--theme-designer-header-background-grayed': 'var(--tw-color-zinc-200)',
  '--theme-designer-close-background': 'var(--tw-color-zinc-200)',
  '--theme-designer-close-background-hover': 'var(--tw-color-zinc-300)',
  '--theme-designer-close-background-active': 'var(--tw-color-zinc-400)',
  '--theme-designer-drag-column-background': 'var(--tw-color-yellow-100)',
  '--theme-designer-select-column-background': 'var(--tw-color-zinc-100)',

  '--theme-statusbar-background': 'var(--tw-color-zinc-200)',
  '--theme-statusbar-foreground': 'var(--tw-color-zinc-700)',
  '--theme-statusbar-background-hover': 'var(--tw-color-zinc-300)',
  '--theme-statusbar-button-background': 'var(--tw-color-zinc-300)',
  '--theme-statusbar-button-foreground': 'var(--tw-color-zinc-700)',
  '--theme-statusbar-icon-error': 'var(--tw-color-red-500)',
  '--theme-statusbar-icon-ok': 'var(--tw-color-green-500)',

  '--theme-aichat-user-background': 'var(--tw-color-blue-50)',
  '--theme-aichat-assistant-background': 'var(--tw-color-zinc-50)',
  '--theme-applog-details-background': 'var(--tw-color-zinc-50)',

  '--theme-input-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-input-border-hover': '1px solid var(--theme-input-border-hover-color)',
  '--theme-input-border-hover-color': 'var(--tw-color-zinc-400)',
  '--theme-input-border-focus': '1px solid var(--theme-input-border-focus-color)',
  '--theme-input-border-focus-color': 'var(--tw-color-blue-500)',
  '--theme-input-border-disabled': '1px solid var(--tw-color-zinc-200)',
  '--theme-input-background': 'white',
  '--theme-input-foreground': 'var(--tw-color-zinc-900)',
  '--theme-input-placeholder': 'var(--tw-color-zinc-400)',
  '--theme-input-background-disabled': 'var(--tw-color-zinc-100)',
  '--theme-input-foreground-disabled': 'var(--tw-color-zinc-400)',
  '--theme-input-focus-ring': '0 0 0 2px color-mix(in srgb, var(--tw-color-blue-500) 15%, transparent)',
  '--theme-input-multi-clear-background': 'var(--tw-color-zinc-200)',
  '--theme-input-multi-clear-foreground': 'var(--tw-color-zinc-600)',
  '--theme-input-multi-clear-hover': 'var(--tw-color-zinc-300)',
  '--theme-input-shadow': 'none',
  '--theme-input-shadow-hover': 'none',
  '--theme-input-shadow-focus': 'none',
  '--theme-input-inplace-select-shadow': '0 1px 6px 1px var(--tw-color-zinc-400)',
  '--theme-color-selected-border': '2px solid var(--tw-color-zinc-700)',

  '--theme-new-object-button-background': 'var(--tw-color-zinc-100)',
  '--theme-new-object-button-background-hover': 'var(--tw-color-zinc-200)',

  '--theme-status-valid-background': 'var(--tw-color-green-50)',
  '--theme-status-testing-background': 'var(--tw-color-amber-50)',
  '--theme-status-error-background': 'var(--tw-color-red-50)',
  '--theme-status-unconfigured-background': 'var(--tw-color-zinc-50)',
  '--theme-status-untested-background': 'var(--tw-color-orange-50)',

  '--theme-dropdown-icon-hover': 'var(--tw-color-blue-700)',
  '--theme-icon-picker-background': 'var(--tw-color-zinc-100)',
  '--theme-icon-picker-border': '1px solid var(--tw-color-zinc-300)',
  '--theme-icon-picker-hover': 'var(--tw-color-zinc-200)',
  '--theme-icon-picker-selected': 'var(--tw-color-blue-200)',
  '--theme-redis-background': 'var(--tw-color-zinc-50)',
  '--theme-redis-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-redis-icon-hover': 'var(--tw-color-zinc-400)',

  '--theme-chip-background': 'var(--tw-color-zinc-200)',
  '--theme-titlebar-background': 'var(--tw-color-zinc-100)',
  '--theme-titlebar-button-hover': 'var(--tw-color-zinc-200)',

  '--theme-card-background': 'var(--tw-color-zinc-50)',
  '--theme-card-border': '1px solid var(--tw-color-zinc-200)',
  '--theme-content-background-hover': 'var(--tw-color-zinc-50)',

  '--theme-admin-menu-item-hover': 'var(--tw-color-zinc-50)',
  '--theme-admin-menu-item-active': 'var(--tw-color-zinc-200)',
  '--theme-admin-menu-background': 'var(--tw-color-zinc-100)',
  '--theme-admin-menu-border': '1px solid var(--tw-color-zinc-200)',

  '--theme-json-tree-string-color': 'var(--tw-color-red-600)',
  '--theme-json-tree-symbol-color': 'var(--tw-color-red-600)',
  '--theme-json-tree-boolean-color': 'var(--tw-color-blue-700)',
  '--theme-json-tree-function-color': 'var(--tw-color-blue-700)',
  '--theme-json-tree-number-color': 'var(--tw-color-indigo-700)',
  '--theme-json-tree-label-color': 'var(--tw-color-purple-700)',
  '--theme-json-tree-arrow-color': 'var(--tw-color-zinc-500)',
  '--theme-json-tree-null-color': 'var(--tw-color-zinc-500)',
  '--theme-json-tree-undefined-color': 'var(--tw-color-zinc-500)',
  '--theme-json-tree-date-color': 'var(--tw-color-zinc-500)',
  '--theme-json-tree-deleted-background': 'var(--tw-color-red-50)',
  '--theme-json-tree-modified-background': 'var(--tw-color-amber-50)',
  '--theme-json-tree-inserted-background': 'var(--tw-color-green-50)',

  '--theme-icon-blue': 'var(--tw-color-blue-600)',
  '--theme-icon-green': 'var(--tw-color-green-600)',
  '--theme-icon-red': 'var(--tw-color-red-600)',
  '--theme-icon-gold': 'var(--tw-color-amber-600)',
  '--theme-icon-yellow': 'var(--tw-color-yellow-600)',
  '--theme-icon-magenta': 'var(--tw-color-pink-600)',

  '--theme-usercolor-foreground-red': 'var(--tw-color-rose-600)',
  '--theme-usercolor-foreground-orange': 'var(--tw-color-orange-600)',
  '--theme-usercolor-foreground-yellow': 'var(--tw-color-yellow-600)',
  '--theme-usercolor-foreground-lime': 'var(--tw-color-lime-600)',
  '--theme-usercolor-foreground-green': 'var(--tw-color-emerald-600)',
  '--theme-usercolor-foreground-cyan': 'var(--tw-color-cyan-600)',
  '--theme-usercolor-foreground-blue': 'var(--tw-color-blue-600)',
  '--theme-usercolor-foreground-purple': 'var(--tw-color-violet-600)',
  '--theme-usercolor-foreground-magenta': 'var(--tw-color-fuchsia-600)',
  '--theme-usercolor-foreground-grey': 'var(--tw-color-gray-600)',

  '--theme-usercolor-background-red': 'var(--tw-color-rose-100)',
  '--theme-usercolor-background-orange': 'var(--tw-color-orange-100)',
  '--theme-usercolor-background-yellow': 'var(--tw-color-yellow-100)',
  '--theme-usercolor-background-lime': 'var(--tw-color-lime-100)',
  '--theme-usercolor-background-green': 'var(--tw-color-emerald-100)',
  '--theme-usercolor-background-cyan': 'var(--tw-color-cyan-100)',
  '--theme-usercolor-background-blue': 'var(--tw-color-blue-100)',
  '--theme-usercolor-background-purple': 'var(--tw-color-violet-100)',
  '--theme-usercolor-background-magenta': 'var(--tw-color-fuchsia-100)',
  '--theme-usercolor-background-grey': 'var(--tw-color-gray-100)',

  '--theme-usercolor-statusbar-red': 'var(--tw-color-rose-600)',
  '--theme-usercolor-statusbar-orange': 'var(--tw-color-orange-600)',
  '--theme-usercolor-statusbar-yellow': 'var(--tw-color-yellow-600)',
  '--theme-usercolor-statusbar-lime': 'var(--tw-color-lime-600)',
  '--theme-usercolor-statusbar-green': 'var(--tw-color-emerald-600)',
  '--theme-usercolor-statusbar-cyan': 'var(--tw-color-cyan-600)',
  '--theme-usercolor-statusbar-blue': 'var(--tw-color-blue-600)',
  '--theme-usercolor-statusbar-purple': 'var(--tw-color-violet-600)',
  '--theme-usercolor-statusbar-magenta': 'var(--tw-color-fuchsia-600)',
  '--theme-usercolor-statusbar-grey': 'var(--tw-color-gray-600)',

  '--token-base': 'white',
  '--token-text': '#333333',
  '--token-comment': '#008000',
  '--token-quote': '#008000',
  '--token-variable': '#008000',
  '--token-keyword': '#0000ff',
  '--token-selector-tag': '#0000ff',
  '--token-built_in': '#0000ff',
  '--token-name': '#0000ff',
  '--token-tag': '#0000ff',
  '--token-string': '#a31515',
  '--token-title': '#a31515',
  '--token-section': '#a31515',
  '--token-attribute': '#a31515',
  '--token-literal': '#a31515',
  '--token-template-tag': '#a31515',
  '--token-template-variable': '#a31515',
  '--token-type': '#a31515',
  '--token-addition': '#a31515',
  '--token-deletion': '#2b91af',
  '--token-selector-attr': '#2b91af',
  '--token-selector-pseudo': '#2b91af',
  '--token-meta': '#2b91af',
  '--token-doctag': '#808080',
  '--token-attr': '#ff0000',
  '--token-symbol': '#00b0e8',
  '--token-bullet': '#00b0e8',
  '--token-link': '#00b0e8',
  '--token-emphasis': 'italic',
  '--token-strong': 'bold',
};
